version: '3.8'

services:
  web-app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: on-failure
  
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
  
volumes:
  redis-data: